--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/thebigsmileXD/Backpack
projects:
  Backpack:
    path: ""
    icon: "resources/github/backpack.png"
    excludeDirs:
    - "resources/github"
    libs:
    - src: CortexPE/Commando/Commando
      version: ^5.0.0
    - src: muqsit/invmenu/InvMenu
      version: ^4.0.0
...
