name: Backpack
main: xenialdan\Backpack\Loader
version: 1.0.1
api: [5.0.0]
author: Clajules09
commands:
  backpack:
    description: Manage your backpack
    usage: /backpack
    permission: backpack.command
permissions:
  backpack.command:
    default: true
  backpack.type:
    description: Permission for backpack types, use backpack.type.name to enable a specific type
    default: true